Feature/add models
noidori/task_manager pull request #2
Opened 2023-03-24 16:39 UTC by noidori

2023-03-27 07:54 UTC, aleksandr-semenov-dbp requested changes
исключить .idea

2023-04-18 22:42 UTC, aleksandr-semenov-dbp approved these changes

2023-04-18 22:44 UTC, aleksandr-semenov-dbp requested changes
После создания/изменения моделей всегда нужно делать миграции. Миграции мы также храним в репозитории

2023-04-19 18:21 UTC, noidori commented
Спасибо. Буду иметь ввиду в дальнейшем.

2023-04-19 19:04 UTC, aleksandr-semenov-dbp approved these changes

2023-04-19 19:17 UTC, merged